- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "Devops"
    Trainer: "Sivakumar"
    Duration: "110HRS"
  tasks: 
  - name: check variables
    vars: #task level
      course: "Devops with AWS"
  ansible.builtin.debug:
    msg: "hi, i am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"